### ISSUE TITLE
High failure rate on 5.x screenshots, DeviceOcr errors on Far count

### ISSUE THREAD

**Issue by JustVldKsh** [283375/arcaea-offline-ocr#11]
Might be an issue with the OCR model you've provided to me by Email, but after some thorough testing I've found out OCR fails on most 5.0+ screenshots while processing Far count. Though, in some (rarer) cases, it does go through, but it is guaranteed to be with incorrect Far count in the score details (mostly x2 saved as 2, but a few times it is being set to 0).
Can provide 300+ screenshots either by Email or DMs, if required

Relevant log:
[arcaea-offline-pyside-ui-20240605-152627_debug.log](https://github.com/user-attachments/files/15580656/arcaea-offline-pyside-ui-20240605-152627_debug.log)

**Comment by 283375** [comment]
That's weird. Could you zip me 10 images which will cause the problem?

**Comment by JustVldKsh** [comment]
Sure, here's a bunch of screenshots
[Screenshot_2024-0.tar.gz](https://github.com/user-attachments/files/15584900/Screenshot_2024-0.tar.gz)

**Comment by 283375** [comment]
Should be working now (at least for the 10 samples provided).
The new version of this ocr core may be applied after solving [this score date issue](https://github.com/ArcaeaOffline/client-pyside6/issues/9), you may close this after verifying the rest of the images won't cause any issues in the new GUI release :)

**Comment by JustVldKsh** [comment]
Works now!
